### ISSUE TITLE
[API Request] 전체 사용자를 위한 Board API

### ISSUE THREAD

**Issue by gaki2** [pjh612/FootBall_Love#100]
## 🥝 요청 API

전체 사용자를 위한 Board Post,get API

## 🌽 설명

**1. POST API**
data : {
      id
      nickname
      title (글제목)
      content (글내용)
      image (이미지, 개수: 최대 1개, 요청 이미지 없을수도 있음)
      time (글 작성 시간)
      recommend (추천수)
}

**2. Get API**

2-1.  글 list 페이지때 사용할 get API

data:
[{
id
nickname
title (글제목)
time(글작성시간)
recommend (추천수)
}...]

![image](https://user-images.githubusercontent.com/76833478/154691461-072320ce-5514-4e31-9610-521b94f1a646.png)

2-2. 글 1개를 클릭한 뒤 글의 정보를 볼 때 사용할 api
data:
{
id
nickname
title (글제목)
content (글내용)
image (이미지, 개수: 최대 1개, 요청 이미지 없을수도 있음)
time (글 작성 시간)
recommend (추천수)
}

![image](https://user-images.githubusercontent.com/76833478/154691527-a69e9cdc-be4a-4651-bca3-9d9d7d71365a.png)

**Comment by SiJun-Yoo** [comment]
기존에 Board Domain을 TeamBoard와 Board로 분리하였습니다.
기존에 Board는 TeamBoard 클래스로서 역할을 수행하고 새로 추가된 Board는 공용 게시판작업과 관련하여 수행하도록 개발 하였습니다.

API또한 Board와 TeamBoard를 분리하여 TeamBoard API는 기존에 Board API를 사용하게 되었고 새로운 BoardAPI는 아래와 같습니다.

게시판 추가
API URL : /api/board
method : post
request body : { String boardName, BoardType boardType}
요청 권한 : 멤버의 Admin권한이 필요합니다.
response : HttpStatusCode 200

게시판 삭제
API URL : /api/board/{boardId}
method : delete
param : Long boardId
요청 권한 : 멤버의 Admin권한이 필요합니다.
response : {Long boardId, Integer status, String message}

**Comment by gaki2** [comment]
user.type 이 ROLE_ADMIN 이여야 게시판 추가 및 삭제가 가능.
그 외 기능은 동일.
