### ISSUE TITLE
[전체사용자 Board 관련 요청사항]

### ISSUE THREAD

**Issue by gaki2** [pjh612/FootBall_Love#110]
## 요청 내용

전체 게시판의 생성자에서 boardName:'notice' , BoardType:'NOTICE' 로 자동 생성되게끔 처리해주셨으면 좋겠습니다.

**Comment by SiJun-Yoo** [comment]
여기에 추가적으로 board목록 api까지 제작하면 되나요

**Comment by SiJun-Yoo** [comment]
코드 작성했고 merge했습니다.
