### ISSUE TITLE
API 요청 (Team 정보 get 하는 api)

### ISSUE THREAD

**Issue by gaki2** [pjh612/FootBall_Love#77]
## 🥝 요청 API

- 팀 정보 get하는 api

  요청 성공시 : 
      teams[team1, team2 ....] 형식
      
      각 팀에 대한 세분화된 정보 :
      team1 {
           teamMemberId,
           teamId,
           teamName,
           memberId,
           authority, 
           board[{boardName, boardId}, {boardName, boardId} ....]  (추가 부탁)
      }

**Comment by pjh612** [comment]
완료

Http Method - GET
URI - /api/team/{teamId}

성공시 200 OK
존재하지 않은 팀 조회 시 400 에러와 함께 "no such Team data" 반환
