### ISSUE TITLE
API 수정요청 [유저정보 get할때 팀정보 없애주세요]

### ISSUE THREAD

**Issue by gaki2** [pjh612/FootBall_Love#91]
## 🥝 요청내용

지금 유저정보 get 하는 api 에서 teams 라는 배열에 팀정보도 같이 오는데, 팀정보는 빼주세요.
그냥 teams 라는 배열 자체가 안 오도록 해주세요.

## 🌽 요청설명

현재 유저정보 get 하는 api 랑 팀 정보 get 하는 api 를 둘다 쓰고있는데, 유저정보 get 할때 팀정보도 같이 와서 두 api 의 리턴 데이터가 겹쳐서 오류가 발생할수도 있을것 같아서 요청드립니다.

**Comment by SiJun-Yoo** [comment]
수정했습니다.
